### ISSUE TITLE
_the_table TEXT := 'bikeways'; refrenced in README but not anywhere else

### ISSUE THREAD

**Issue by easherma** [radumas/bikeways4everybody#66]
Is this comment still relevant, or is the table name defined somewhere else? I have forked off a version of this, but am having trouble getting the sql query to POST.

**Comment by radumas** [comment]
The value of `_the_table` should be equal to the name of the table you create in Carto.

(I haven't played with Carto since they rebranded, so I don't know if there are other issues with the coding of the project)

**Comment by easherma** [comment]
I think this is confusing in the docs, becuase your code has the name of the table hard-coded and there is no _the_table entry anywhere (unless I'm missing it).

Either way, thanks for the project!

**Comment by radumas** [comment]
ahhhh. I see what you mean.
